#!/bin/bash

set -e

#sudo qemu-system-x86_64 -hda system.raw -hdb data.raw -net nic -net user -m 1024M -localtime -enable-kvm -nographic -kernel vmlinuz -initrd initrd.img -append "ks=file:///fedora20.ks"
sudo qemu-system-x86_64 -hda system.raw -hdb data.raw -net nic -net user -m 1024M -localtime -enable-kvm
