#!/bin/bash

set -euo pipefail

BASE_DIR=$(dirname `readlink -e $0`)
sudo qemu-system-x86_64 \
    -drive file=${BASE_DIR}/system.qcow2,format=qcow2,index=0,media=disk     \
    -net nic -net user  \
    -m 1024M            \
    -localtime          \
    -enable-kvm         \
    -redir tcp:2223::22 \
    -redir tcp:8889::80 \
    -nographic          \
    -virtfs local,path=$HOME,security_model=passthrough,mount_tag=host_home_dir 2>&1 > /dev/null < /dev/null &
# mount -t 9p -o trans=virtio host_share /opt/src -oversion=9p2000.L
